language: python

services:
  - docker

before_install:
  - docker pull mongo:latest

python:

  - "2.7"

script: 
  - curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
  - chmod u+x lw-scanner
  - lw-scanner
